name: blox3-test
services:
  postgres:
    image: postgres:14
    container_name: postgres-test
    ports:
      - 5433:5432
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'blox3-test' ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_PASSWORD: blox3-test
      POSTGRES_USER: blox3-test
      POSTGRES_DB: blox3-test
  redis:
    image: redis
    container_name: redis-test
    ports:
      - 6378:6379
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 30s
      retries: 3
