name: ezwallet
services:
  ezwallet-postgres:
    image: postgres:14
    container_name: ezwallet-db
    ports:
      - 5678:5432
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'ezwallet' ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_PASSWORD: ezwallet
      POSTGRES_USER: ezwallet
      POSTGRES_DB: ezwallet
  redis:
    image: redis
    container_name: ezwallet-redis
    ports:
      - 6380:6379
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 30s
      retries: 3
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: ezwallet-redis_commander
    environment:
      - REDIS_HOSTS=redis:redis:6380
    ports:
      - 8082:8081
    depends_on:
      - redis    