export default {
  verbose: true,
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: './',
  testEnvironment: 'node',
  testTimeout: 30000,
  setupFilesAfterEnv: ['./test/setup-app.ts'],
  testRegex: '.spec.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['./src/**/*.(t|j)s'],
  coveragePathIgnorePatterns: [
    '.module.ts',
    '<rootDir>/src/config/*',
    '<rootDir>/src/main.ts',
    '.mock.ts',
  ],
  moduleNameMapper: {
    '@blox3/infra-auth/(.*)': '<rootDir>/libs/infra-auth/src/$1',
    '@blox3/infra-auth': '<rootDir>/libs/infra-auth/src',
    '@blox3/infra-exception/(.*)': '<rootDir>/libs/infra-exception/src/$1',
    '@blox3/infra-exception': '<rootDir>/libs/infra-exception/src',
    '@blox3/infra-common/(.*)': '<rootDir>/libs/infra-common/src/$1',
    '@blox3/infra-common': '<rootDir>/libs/infra-common/src',
    '@blox3/infra-modules/(.*)': '<rootDir>/libs/infra-modules/src/$1',
    '@blox3/infra-modules': '<rootDir>/libs/infra-modules/src',
    'database/entities/(.*)': '<rootDir>/database/entities/$1',
    'database/entities': '<rootDir>/database/entities',
    'database/transformers/(.*)': '<rootDir>/database/entities/$1',
    'database/transformers': '<rootDir>/database/transformers',
    'database/enums/(.*)': '<rootDir>/database/enums/$1',
    'database/enums': '<rootDir>/database/enums',
    'src/(.*)': '<rootDir>/src/$1',
  },
};
