export enum MailType {
  OTP_RE_LOGIN = 'OTP_RE_LOGIN',
  OTP_SIGN_UP = 'OTP_SIGN_UP',
  OTP_PASSWORD_CHANGE = 'OTP_PASSWORD_CHANGE',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  INCOMING_DEPOSIT = 'INCOMING_DEPOSIT',
  DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS',
  WITHDRAW_REQUEST = 'WITHDRAW_REQUEST',
  CHANGING_PASSWORD = 'CHANGING_PASSWORD',
  CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS',
}
